export const INIT = 'EXPERIENCE_MATERIAL_WEEK_INIT';
export const REQUEST = 'EXPERIENCE_MATERIAL_WEEK_REQUEST';
export const RECEIVED = 'EXPERIENCE_MATERIAL_WEEK_RECEIVED';
export const ERROR = 'EXPERIENCE_MATERIAL_WEEK_ERROR';
