export const INIT = 'INVESTMENT_MARKETING_STOCK_INIT';
export const REQUEST = 'INVESTMENT_MARKETING_STOCK_REQUEST';
export const RECEIVED = 'INVESTMENT_MARKETING_STOCK_RECEIVED';
export const ERROR = 'INVESTMENT_MARKETING_STOCK_ERROR';
