export const INIT = 'COMPREHENSIVE_STRENGTH_TEACHER_INIT';
export const REQUEST = 'COMPREHENSIVE_STRENGTH_TEACHER_REQUEST';
export const RECEIVED = 'COMPREHENSIVE_STRENGTH_TEACHER_RECEIVED';
export const ERROR = 'COMPREHENSIVE_STRENGTH_TEACHER_ERROR';
