export const INIT = 'COMPREHENSIVE_STRATEGY_LHDLD_INIT';
export const REQUEST = 'COMPREHENSIVE_STRATEGY_LHDLD_REQUEST';
export const RECEIVED = 'COMPREHENSIVE_STRATEGY_LHDLD_RECEIVED';
export const ERROR = 'COMPREHENSIVE_STRATEGY_LHDLD_ERROR';
