export const INIT = 'COMPREHENSIVE_MARKETING_ARTICLE_INIT';
export const REQUEST = 'COMPREHENSIVE_MARKETING_ARTICLE_REQUEST';
export const RECEIVED = 'COMPREHENSIVE_MARKETING_ARTICLE_RECEIVED';
export const ERROR = 'COMPREHENSIVE_MARKETING_ARTICLE_ERROR';
