export const INIT = 'COMPREHENSIVE_EXPERIENCE_QSYXD_INIT';
export const REQUEST = 'COMPREHENSIVE_EXPERIENCE_QSYXD_REQUEST';
export const RECEIVED = 'COMPREHENSIVE_EXPERIENCE_QSYXD_RECEIVED';
export const ERROR = 'COMPREHENSIVE_EXPERIENCE_QSYXD_ERROR';
