export const INIT = 'COMPREHENSIVE_STRENGTH_COMPANY_INIT';
export const REQUEST = 'COMPREHENSIVE_STRENGTH_COMPANY_REQUEST';
export const RECEIVED = 'COMPREHENSIVE_STRENGTH_COMPANY_RECEIVED';
export const ERROR = 'COMPREHENSIVE_STRENGTH_COMPANY_ERROR';
