export const INIT = 'STRATEGY_MATERIAL_REVIEW_INIT';
export const REQUEST = 'STRATEGY_MATERIAL_REVIEW_REQUEST';
export const RECEIVED = 'STRATEGY_MATERIAL_REVIEW_RECEIVED';
export const ERROR = 'STRATEGY_MATERIAL_REVIEW_ERROR';
