export const INIT = 'COMPREHENSIVE_STRENGTH_PRODUCT_INIT';
export const REQUEST = 'COMPREHENSIVE_STRENGTH_PRODUCT_REQUEST';
export const RECEIVED = 'COMPREHENSIVE_STRENGTH_PRODUCT_RECEIVED';
export const ERROR = 'COMPREHENSIVE_STRENGTH_PRODUCT_ERROR';
