export const INIT = 'RESEARCH_MATERIAL_INIT';
export const REQUEST = 'RESEARCH_MATERIAL_REQUEST';
export const REQUEST_PRIMARY = 'RESEARCH_MATERIAL_REQUEST_PRIMARY';
export const REQUEST_CONCENTRATE = 'RESEARCH_MATERIAL_REQUEST_CONCENTRATE';
export const RECEIVED = 'RESEARCH_MATERIAL_RECEIVED';
export const ERROR = 'RESEARCH_MATERIAL_ERROR';
