export const INIT = 'COMPREHENSIVE_MARKETING_SPEECH_CRAFT_INIT';
export const REQUEST = 'COMPREHENSIVE_MARKETING_SPEECH_CRAFT_REQUEST';
export const RECEIVED = 'COMPREHENSIVE_MARKETING_SPEECH_CRAFT_RECEIVED';
export const ERROR = 'COMPREHENSIVE_MARKETING_SPEECH_CRAFT_ERROR';
