export const INIT = 'COMPREHENSIVE_STRENGTH_LICENCE_INIT';
export const REQUEST = 'COMPREHENSIVE_STRENGTH_LICENCE_REQUEST';
export const RECEIVED = 'COMPREHENSIVE_STRENGTH_LICENCE_RECEIVED';
export const ERROR = 'COMPREHENSIVE_STRENGTH_LICENCE_ERROR';
