export const INIT = 'COMPREHENSIVE_STRATEGY_QSYXD_INIT';
export const REQUEST = 'COMPREHENSIVE_STRATEGY_QSYXD_REQUEST';
export const RECEIVED = 'COMPREHENSIVE_STRATEGY_QSYXD_RECEIVED';
export const ERROR = 'COMPREHENSIVE_STRATEGY_QSYXD_ERROR';
