export const INIT = 'INVESTMENT_SERVICE_STOCK_INIT';
export const REQUEST = 'INVESTMENT_SERVICE_STOCK_REQUEST';
export const RECEIVED = 'INVESTMENT_SERVICE_STOCK_RECEIVED';
export const CONDITION = 'INVESTMENT_SERVICE_STOCK_CONDITION';
export const ORDER = 'INVESTMENT_SERVICE_STOCK_ORDER';
export const ERROR = 'INVESTMENT_SERVICE_STOCK_ERROR';
