export const INIT = 'COMPREHENSIVE_CUSTOM_VIDEO_INIT';
export const REQUEST = 'COMPREHENSIVE_CUSTOM_VIDEO_REQUEST';
export const RECEIVED = 'COMPREHENSIVE_CUSTOM_VIDEO_RECEIVED';
export const ERROR = 'COMPREHENSIVE_CUSTOM_VIDEO_ERROR';
