export const INIT = 'MARKETING_MATERIAL_PRODUCT_INIT';
export const REQUEST = 'MARKETING_MATERIAL_PRODUCT_REQUEST';
export const RECEIVED = 'MARKETING_MATERIAL_PRODUCT_RECEIVED';
export const ERROR = 'MARKETING_MATERIAL_PRODUCT_ERROR';
