export const INIT = 'INVESTMENT_TEXT_STRATEGY_INIT';
export const REQUEST = 'INVESTMENT_TEXT_STRATEGY_REQUEST';
export const RECEIVED = 'INVESTMENT_TEXT_STRATEGY_RECEIVED';
export const ERROR = 'INVESTMENT_TEXT_STRATEGY_ERROR';
