export const INIT = 'COMPREHENSIVE_EXPERIENCE_LHDLD_INIT';
export const REQUEST = 'COMPREHENSIVE_EXPERIENCE_LHDLD_REQUEST';
export const RECEIVED = 'COMPREHENSIVE_EXPERIENCE_LHDLD_RECEIVED';
export const ERROR = 'COMPREHENSIVE_EXPERIENCE_LHDLD_ERROR';
