export const INIT = 'CUSTOMER_SERVICE_VIDEO_INIT';
export const REQUEST = 'CUSTOMER_SERVICE_VIDEO_REQUEST';
export const RECEIVED = 'CUSTOMER_SERVICE_VIDEO_RECEIVED';
export const ERROR = 'CUSTOMER_SERVICE_VIDEO_ERROR';
