const childProducts = {
  title:'请选择子产品',
  subs:[
    {
      id:'duanXianBao',
      key:'duanXianBao',
      text:'短线宝'
    },
    {
      id:'junYinCaoPan',
      key:'junYinCaoPan',
      text:'君银操盘'
    },
    {
      id:'junYinYanJiu',
      key:'junYinYanJiu',
      text:'君银研究'
    }
  ]
};

export default {
  title:'请选择分类',
  subs:[
    {
      id:'product',
      key:'product',
      text:'产品素材',
      title:'请选择产品',
      subs:[
        {
          id:'team_QSYX',
          key:'team_QSYX',
          text:'强势优选组',
          ...childProducts
        },
        {
          id:'team_NYTZ',
          key:'team_NYTZ',
          text:'牛眼投资组',
          ...childProducts
        },
        {
          id:'team_QSXG',
          key:'team_QSXG',
          text:'强势选股组',
          ...childProducts
        },
        {
          id:'team_DLLH',
          key:'team_DLLH',
          text:'独立量化组',
          ...childProducts
        }
      ]
    },
    {
      id:'comprehensive',
      key:'comprehensive',
      text:'综合素材',
      title:'请选择产品',
      subs:[
        {
          id:'marketing',
          key:'marketing',
          text:'营销素材'
        },
        {
          id:'investment',
          key:'investment',
          text:'投资组合'
        },
      ]
    }
  ]
}
