export const INIT = 'LIVE_VIDEO_CHAT_INIT';
export const REQUEST = 'LIVE_VIDEO_CHAT_REQUEST';
export const RECEIVED = 'LIVE_VIDEO_CHAT_RECEIVED';
export const ADD = 'LIVE_VIDEO_CHAT_ADD';
export const ADD_SUCCESS = 'LIVE_VIDEO_CHAT_SUCCESS';
export const ERROR = 'LIVE_VIDEO_CHAT_ERROR';
