export const INIT = 'RESEARCH_MATERIAL_INIT';
export const GET_TOTAL = 'RESEARCH_MATERIAL_GET_TOTAL';
export const REQUEST_PRIMARY = 'RESEARCH_MATERIAL_PRIMARY_REQUEST';
export const REQUEST_CONCENTRATE = 'RESEARCH_MATERIAL_CONCENTRATE_REQUEST';
export const RECEIVED_PRIMARY = 'RESEARCH_MATERIAL_PRIMARY_RECEIVED';
export const RECEIVED_CONCENTRATE = 'RESEARCH_MATERIAL_CONCENTRATE_RECEIVED';
export const ERROR = 'RESEARCH_MATERIAL_ERROR';
