export const INIT = 'EXPERIENCE_MATERIAL_YEAR_INIT';
export const REQUEST = 'EXPERIENCE_MATERIAL_YEAR_REQUEST';
export const RECEIVED = 'EXPERIENCE_MATERIAL_YEAR_RECEIVED';
export const ERROR = 'EXPERIENCE_MATERIAL_YEAR_ERROR';
