export const INIT = 'STRATEGY_MATERIAL_ANALYSIS_INIT';
export const REQUEST = 'STRATEGY_MATERIAL_ANALYSIS_REQUEST';
export const RECEIVED = 'STRATEGY_MATERIAL_ANALYSIS_RECEIVED';
export const ERROR = 'STRATEGY_MATERIAL_ANALYSIS_ERROR';
