export const INIT = 'PRODUCT_CUSTOMER_SERVICE_ANALYSIS_INIT';
export const REQUEST = 'PRODUCT_CUSTOMER_SERVICE_ANALYSIS_REQUEST';
export const RECEIVED = 'PRODUCT_CUSTOMER_SERVICE_ANALYSIS_RECEIVED';
export const ERROR = 'PRODUCT_CUSTOMER_SERVICE_ANALYSIS_ERROR';
