export const INIT = 'CUSTOMER_SERVICE_ANALYSIS_INIT';
export const REQUEST = 'CUSTOMER_SERVICE_ANALYSIS_REQUEST';
export const RECEIVED = 'CUSTOMER_SERVICE_ANALYSIS_RECEIVED';
export const ERROR = 'CUSTOMER_SERVICE_ANALYSIS_ERROR';
