export const INIT = 'STRATEGY_MATERIAL_PREDICTION_INIT';
export const REQUEST = 'STRATEGY_MATERIAL_PREDICTION_REQUEST';
export const RECEIVED = 'STRATEGY_MATERIAL_PREDICTION_RECEIVED';
export const ERROR = 'STRATEGY_MATERIAL_PREDICTION_ERROR';
