export const INIT = 'LEAVE_MESSAGE_INIT';
export const REQUEST = 'LEAVE_MESSAGE_REQUEST';
export const RECEIVED = 'LEAVE_MESSAGE_RECEIVED';
export const ADD = 'LEAVE_MESSAGE_ADD';
export const ADD_SUCCESS = 'LEAVE_MESSAGE_ADD_SUCCESS';
export const ERROR = 'LEAVE_MESSAGE_ERROR';
