export const INIT = 'MARKETING_MATERIAL_RECORD_INIT';
export const REQUEST = 'MARKETING_MATERIAL_RECORD_REQUEST';
export const RECEIVED = 'MARKETING_MATERIAL_RECORD_RECEIVED';
export const ERROR = 'MARKETING_MATERIAL_RECORD_ERROR';
