export const INIT = 'COMPREHENSIVE_MARKETING_IMAGE_INIT';
export const REQUEST = 'COMPREHENSIVE_MARKETING_IMAGE_REQUEST';
export const RECEIVED = 'COMPREHENSIVE_MARKETING_IMAGE_RECEIVED';
export const ERROR = 'COMPREHENSIVE_MARKETING_IMAGE_ERROR';
