export const TOTAL = 'SIDER_MEN_FOR_PRODUCT_TOTAL';
export const REQUEST = 'SIDER_MENU_FOR_PRODUCT_TOTAL_REQUEST';
export const RECEIVED = 'SIDER_MENU_FOR_PRODUCT_TOTAL_RECEIVED';
export const ERROR = 'SIDER_MENU_FOR_PRODUCT_TOTAL_ERROR';

export const BEFORE = 'SIDER_MENU_FOR_PRODUCT_TOTAL_CHANGE_BEFORE';
export const INIT_BEFORE = 'SIDER_MENU_FOR_PRODUCT_TOTAL_CHANGE_INIT_BEFORE';
