export const TOTAL = 'SIDER_MENU_TOTAL';
export const REQUEST = 'SIDER_MENU_TOTAL_REQUEST';
export const RECEIVED = 'SIDER_MENU_TOTAL_RECEIVED';
export const ERROR = 'SIDER_MENU_TOTAL_ERROR';

export const BEFORE = 'SIDER_MENU_TOTAL_CHANGE_BEFORE';
